// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbrp36jO209pfaK39WfGTalOg6SOIYbvU',
    appId: '1:398644073089:web:a1f65a8a5aaa35d55ab380',
    messagingSenderId: '398644073089',
    projectId: 'thick-cf6c2',
    authDomain: 'thick-cf6c2.firebaseapp.com',
    storageBucket: 'thick-cf6c2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYRghrD_Jbs1-LDibF0e6eG7c2LHBYZOs',
    appId: '1:398644073089:android:4edcc285916504e05ab380',
    messagingSenderId: '398644073089',
    projectId: 'thick-cf6c2',
    storageBucket: 'thick-cf6c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa5LvjtcETM2N_uyYKzWQRE9va8PFTKNw',
    appId: '1:398644073089:ios:fe0bd9845edf5a5b5ab380',
    messagingSenderId: '398644073089',
    projectId: 'thick-cf6c2',
    storageBucket: 'thick-cf6c2.firebasestorage.app',
    iosBundleId: 'com.example.thick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa5LvjtcETM2N_uyYKzWQRE9va8PFTKNw',
    appId: '1:398644073089:ios:fe0bd9845edf5a5b5ab380',
    messagingSenderId: '398644073089',
    projectId: 'thick-cf6c2',
    storageBucket: 'thick-cf6c2.firebasestorage.app',
    iosBundleId: 'com.example.thick',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbrp36jO209pfaK39WfGTalOg6SOIYbvU',
    appId: '1:398644073089:web:de78e8e0262cb4a85ab380',
    messagingSenderId: '398644073089',
    projectId: 'thick-cf6c2',
    authDomain: 'thick-cf6c2.firebaseapp.com',
    storageBucket: 'thick-cf6c2.firebasestorage.app',
  );

}